---
title: "Web Analytics"
description: "Fallstudie"
author:
  - name: Prof. Dr. Jan Kirenz 
    affiliation: HdM Stuttgart
output:
  distill::distill_article:
    toc: yes
    toc_depth: 3
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

*Die Lösung der Aufgaben soll anhand von Screenshots und Kommentaren in einer Präsentation dokumentiert werden (pro Gruppenmitglied mindestens 10 Seiten)*


Versetzen Sie sich bei den folgenden Aufgaben in die Rolle einer/eines Mitarbeiterin im Bereich Web Analytics. 

- Folgende Online-Präsenz soll analysiert werden: [Google Merchandise Store](https://your.googlemerchandisestore.com/Index)

- Zeitraum: letzte 90 Tage


# Akquisition



# Präsentation

Erstellen Sie eine Präsentation, in welcher folgende Inhalte behandelt werden.

- Anaylsen

Zeitraum: letzte 90 Tage

- Mit welcher Artikelkategorie wurde der höchste Umsatz erzielt?



## See Think Do Framework (30%)

- Ausführliche Anwendung des **See-Think-Do-Frameworks** auf eine spezifische Webseite (siehe unten) und Auswahl von geeigneten Kennzahlen für die Stufen des See-Think-Do-Frameworks (mindestens 4 pro Stufe). 

- Begründen Sie, weshalb die Kennzahlen ausgewählt wurden. 

- Geben Sie zudem für einige der Kennzahlen an, welche Größenordnung (bspw. Anzahl an Besuchern pro Woche) Ihnen realistisch erscheinen würde. 



## Messung der Kennzahlen

Darstellung (mit Hilfe von Screenshots) der mit Hilfe von Google Analytics Technologien umgesetzten Trackinglösungen (aus der Aufgabe Implementierung Tracking). 

Zeigen Sie mit Hilfe von Screenshots, wie die Kennzahlen in Google Analytics gemessen werden können und erstellen Sie zudem ein beispielhaften benutzerdefinierten Bericht (als Tabelle) in Google Analytics. 

Nutzen Sie dabei als Beispiel das Demo-Konto von Google Analytics. Verwenden Sie als Dimensionen zumindest die folgenden Kriterien: Land, Gerätekategorie, Traffic-Typ. Beschreiben Sie beispielhaft, welche Erkenntnisse gewonnen werden können. (30%)

<aside>
[Demo-Konto](https://support.google.com/analytics/answer/6367342?hl=de) von Google Analytics
</aside>

## Dashboard

Erstellen Sie ein Dashboard in **Google Data Studio**, in welchem Sie die Kennzahlen visualisieren. 

Verbinden Sie dafür Google Analytics mit dem Data Studio. (20%)

<aside>
Hinweise zu [Google Data Studio](https://support.google.com/datastudio/answer/6283323?hl=de)
</aside>



In den unten aufgeführten Kapiteln finden Sie Unterlagen und Literaturhinweise für die Bearbeitung der Aufgabenstellungen. 


# Technologien

Beachten Sie unbedingt alle relevanten Unterlagen des Kurses.

<aside>
[Unterlagen](https://docs.google.com/spreadsheets/d/1r_BJFs4Ae4L0o3c7JfIHV4KlCpMYwHJrUk5lYOLu0QY/edit?usp=sharing) in dem Moodle-Kurs der Veranstaltung.
</aside>

## Google Data Studio

Mit Data Studio können Sie aussagekräftige, übersichtliche Dashboards und Berichte erstellen, teilen und an Ihre Bedürfnisse anpassen. Das Tool ist kostenlos. 

<aside>
Hinweise zu [Google Data Studio](https://support.google.com/datastudio/answer/6283323?hl=de)
</aside>
